
name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.ecommatrix.xyz
        username: multivendor2025@multivendor2025.ecommatrix.xyz
        password: multivendor2025
        local-dir: ./
        server-dir: /
        exclude: .gitignore
